version: '3.1'

services:
  #
  # The database we are using to store events
  #
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: esipam
      POSTGRES_USER: esipam_user
      POSTGRES_PASSWORD: secret_saucey
    volumes:
      - './db:/docker-entrypoint-initdb.d'

  #
  # DB Query tool (simple/works)
  #
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080      
